# ElastAlert2 configuration for KlikkFlow log alerting

# Basic configuration
es_host: elasticsearch
es_port: 9200
es_username: elastic
es_password: elastic123

# Index for storing ElastAlert metadata
writeback_index: elastalert_status
writeback_alias: elastalert_alerts

# How often ElastAlert will query Elasticsearch
run_every:
  minutes: 1

# ElastAlert will buffer results from the most recent period
buffer_time:
  minutes: 15

# Optional URL for elasticsearch with basic auth
# es_url_prefix: elasticsearch

# Connect with TLS to Elasticsearch
use_ssl: false
verify_certs: false

# GET request with body is the default option for Elasticsearch.
# If it fails try to set 'use_get_request_with_body: false'
use_get_request_with_body: true

# Option basic-auth username and password for Elasticsearch
# es_username: someusername
# es_password: somepassword

# Rules folder
rules_folder: /opt/elastalert/rules

# How many seconds ElastAlert will wait between queries to Elasticsearch
scan_subdirectories: true

# Logging configuration
logging:
  version: 1
  incremental: false
  disable_existing_loggers: false
  formatters:
    logline:
      format: '%(asctime)s %(levelname)s %(name)s %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: logline
      level: DEBUG
      stream: ext://sys.stdout
    file:
      class: logging.handlers.RotatingFileHandler
      formatter: logline
      level: INFO
      filename: /opt/elastalert/logs/elastalert.log
      maxBytes: 10485760
      backupCount: 5
  loggers:
    elastalert:
      level: INFO
      handlers: [console, file]
      propagate: false
    elasticsearch:
      level: WARN
      handlers: [console]
      propagate: false
    elasticsearch.trace:
      level: WARN
      handlers: [console]
      propagate: false
    '':
      level: INFO
      handlers: [console]
      propagate: false

# Email settings (SMTP)
smtp_host: localhost
smtp_port: 587
smtp_ssl: false
smtp_auth_file: /opt/elastalert/smtp_auth.yaml
email_reply_to: noreply@klikkflow.com
from_addr: alerts@klikkflow.com

# Slack settings
slack_webhook_url: https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK
slack_username_override: ElastAlert
slack_emoji_override: ':exclamation:'
slack_channel_override: '#alerts'

# PagerDuty settings
pagerduty_service_key: YOUR_PAGERDUTY_SERVICE_KEY
pagerduty_client_name: ElastAlert

# Jira settings (if needed)
# jira_server: https://your-domain.atlassian.net
# jira_project: ALERT
# jira_issuetype: Bug

# HipChat settings (if needed)
# hipchat_auth_token: YOUR_HIPCHAT_AUTH_TOKEN
# hipchat_room_id: YOUR_ROOM_ID

# Telegram settings (if needed)
# telegram_bot_token: YOUR_BOT_TOKEN
# telegram_room_id: YOUR_CHAT_ID

# Microsoft Teams settings (if needed)
# ms_teams_webhook_url: YOUR_TEAMS_WEBHOOK_URL

# Custom alerter settings
alerters:
  - "elastalert_modules.custom_alerter.SlackAlerter"
  - "elastalert_modules.custom_alerter.WebhookAlerter"

# Enhancements
enhancements:
  - "elastalert_modules.enhancement.TimeEnhancement"
  - "elastalert_modules.enhancement.PercentMatchEnhancement"

# Time zone
timezone: UTC

# Query delay
max_query_size: 100000

# Aggregation delay
aggregation_delay:
  minutes: 0

# Old query hours
old_query_hours: 24

# Disable rules on error
disable_rules_on_error: false

# Notify email
# notify_email:
#   - admin@klikkflow.com