# ============================================
# AlertManager Configuration
# KlikkFlow Monitoring Stack
# ============================================

global:
  resolve_timeout: 5m

# Route tree
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'default-receiver'

  routes:
    - match:
        severity: critical
      receiver: 'critical-receiver'
      continue: true

    - match:
        severity: warning
      receiver: 'warning-receiver'

# Receivers
receivers:
  - name: 'default-receiver'
    # No notifications configured - add webhook, email, or Slack here

  - name: 'critical-receiver'
    # Configure critical alert receiver (Slack, PagerDuty, etc.)
    # Example Slack:
    # slack_configs:
    #   - api_url: 'YOUR_SLACK_WEBHOOK_URL'
    #     channel: '#critical-alerts'
    #     title: '🚨 Critical Alert'
    #     text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'

  - name: 'warning-receiver'
    # Configure warning alert receiver
    # Example Slack:
    # slack_configs:
    #   - api_url: 'YOUR_SLACK_WEBHOOK_URL'
    #     channel: '#alerts'
    #     title: '⚠️ Warning'
    #     text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'

# Inhibition rules
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']
