# ============================================
# Prometheus Configuration
# Reporunner Monitoring Stack
# ============================================

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'reporunner'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Rule files
rule_files:
  - '/etc/prometheus/rules/*.yml'

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # Backend API metrics
  - job_name: 'backend'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'backend:3001'
          - 'backend-2:3001'
        labels:
          service: 'backend'
          app: 'reporunner'

  # Node Exporter (system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'node-exporter'

  # MongoDB Exporter
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb-exporter:9216']
        labels:
          service: 'mongodb'
          database: 'mongodb'

  # Redis Exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis'
          database: 'redis'

  # Nginx Exporter (via stub_status)
  - job_name: 'nginx'
    metrics_path: '/nginx_status'
    static_configs:
      - targets: ['nginx-lb:80']
        labels:
          service: 'nginx-lb'

  # BullMQ Worker metrics (if exposed)
  - job_name: 'worker'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'worker:3001'
          - 'worker-2:3001'
        labels:
          service: 'worker'
          app: 'reporunner'

  # Grafana self-monitoring
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
        labels:
          service: 'grafana'
