apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reporunner.fullname" . }}-frontend
  labels:
    {{- $component := "frontend" }}
    {{- include "reporunner.componentLabels" (dict "Chart" .Chart "Release" .Release "Values" .Values "component" $component) | nindent 4 }}
spec:
  {{- if not .Values.reporunner.frontend.autoscaling.enabled }}
  replicas: {{ .Values.reporunner.frontend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "reporunner.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "reporunner.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- include "reporunner.podSecurityContext" . | nindent 8 }}
      containers:
        - name: frontend
          securityContext:
            {{- include "reporunner.containerSecurityContext" . | nindent 12 }}
          image: {{ include "reporunner.image" (dict "Chart" .Chart "Values" .Values "repository" .Values.reporunner.frontend.image.repository "tag" .Values.reporunner.frontend.image.tag) }}
          imagePullPolicy: {{ .Values.reporunner.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: VITE_API_URL
              value: "https://{{ (index .Values.ingress.hosts 0).host }}/api"
            - name: VITE_WS_URL
              value: "wss://{{ (index .Values.ingress.hosts 0).host }}/ws"
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            {{- toYaml .Values.reporunner.frontend.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: cache
              mountPath: /var/cache/nginx
            - name: run
              mountPath: /var/run
      volumes:
        - name: tmp
          emptyDir: {}
        - name: cache
          emptyDir: {}
        - name: run
          emptyDir: {}
      {{- with .Values.reporunner.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.reporunner.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.reporunner.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}