apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reporunner.fullname" . }}-backend
  labels:
    {{- $component := "backend" }}
    {{- include "reporunner.componentLabels" (dict "Chart" .Chart "Release" .Release "Values" .Values "component" $component) | nindent 4 }}
spec:
  {{- if not .Values.reporunner.backend.autoscaling.enabled }}
  replicas: {{ .Values.reporunner.backend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "reporunner.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      labels:
        {{- include "reporunner.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- include "reporunner.podSecurityContext" . | nindent 8 }}
      initContainers:
        - name: wait-for-postgresql
          image: postgres:16-alpine
          command:
            - sh
            - -c
            - |
              until pg_isready -h {{ include "reporunner.fullname" . }}-postgresql -p 5432; do
                echo "Waiting for PostgreSQL..."
                sleep 2
              done
        - name: wait-for-mongodb
          image: mongo:7.0
          command:
            - sh
            - -c
            - |
              until mongosh --host {{ include "reporunner.fullname" . }}-mongodb --port 27017 --eval "db.adminCommand('ping')"; do
                echo "Waiting for MongoDB..."
                sleep 2
              done
        - name: wait-for-redis
          image: redis:7-alpine
          command:
            - sh
            - -c
            - |
              until redis-cli -h {{ include "reporunner.fullname" . }}-redis-master -p 6379 ping; do
                echo "Waiting for Redis..."
                sleep 2
              done
      containers:
        - name: backend
          securityContext:
            {{- include "reporunner.containerSecurityContext" . | nindent 12 }}
          image: {{ include "reporunner.image" (dict "Chart" .Chart "Values" .Values "repository" .Values.reporunner.backend.image.repository "tag" .Values.reporunner.backend.image.tag) }}
          imagePullPolicy: {{ .Values.reporunner.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
          env:
            - name: NODE_ENV
              value: {{ .Values.reporunner.env.NODE_ENV }}
            - name: PORT
              value: "3001"
            - name: LOG_LEVEL
              value: {{ .Values.reporunner.env.LOG_LEVEL }}
            - name: CORS_ORIGIN
              value: {{ .Values.reporunner.env.CORS_ORIGIN }}
            - name: DATABASE_URL
              value: {{ include "reporunner.postgresql.connectionString" . }}
            - name: MONGODB_URI
              value: {{ include "reporunner.mongodb.connectionString" . }}
            - name: REDIS_URL
              value: {{ include "reporunner.redis.connectionString" . }}
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "reporunner.fullname" . }}-secrets
                  key: jwt-secret
            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "reporunner.fullname" . }}-secrets
                  key: jwt-refresh-secret
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            {{- toYaml .Values.reporunner.backend.resources | nindent 12 }}
          volumeMounts:
            - name: logs
              mountPath: /app/logs
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: logs
          {{- if .Values.persistence.logs.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "reporunner.fullname" . }}-logs
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: tmp
          emptyDir: {}
      {{- with .Values.reporunner.backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.reporunner.backend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.reporunner.backend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}