{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "reporunner.fullname" . }}-backend
  labels:
    {{- include "reporunner.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  podSelector:
    matchLabels:
      {{- include "reporunner.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  policyTypes:
    - Ingress
    - Egress
  {{- if .Values.networkPolicy.ingress.enabled }}
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "reporunner.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: frontend
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
      ports:
        - protocol: TCP
          port: 3001
  {{- end }}
  {{- if .Values.networkPolicy.egress.enabled }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              {{- include "reporunner.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 5432  # PostgreSQL
        - protocol: TCP
          port: 27017 # MongoDB
        - protocol: TCP
          port: 6379  # Redis
    - to: []  # Allow external API calls
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
  {{- end }}

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "reporunner.fullname" . }}-frontend
  labels:
    {{- include "reporunner.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  podSelector:
    matchLabels:
      {{- include "reporunner.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  policyTypes:
    - Ingress
    - Egress
  {{- if .Values.networkPolicy.ingress.enabled }}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
      ports:
        - protocol: TCP
          port: 80
  {{- end }}
  {{- if .Values.networkPolicy.egress.enabled }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              {{- include "reporunner.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: backend
      ports:
        - protocol: TCP
          port: 3001
  {{- end }}

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "reporunner.fullname" . }}-worker
  labels:
    {{- include "reporunner.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  podSelector:
    matchLabels:
      {{- include "reporunner.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  policyTypes:
    - Egress
  {{- if .Values.networkPolicy.egress.enabled }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              {{- include "reporunner.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 5432  # PostgreSQL
        - protocol: TCP
          port: 27017 # MongoDB
        - protocol: TCP
          port: 6379  # Redis
    - to: []  # Allow external API calls for integrations
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
  {{- end }}
{{- end }}