# ElastAlert rules for KlikkFlow application monitoring

# High error rate alert
- name: "KlikkFlow High Error Rate"
  type: frequency
  index: klikkflow-logs-*
  num_events: 10
  timeframe:
    minutes: 5

  filter:
  - terms:
      log_level: ["error", "fatal"]
  - terms:
      service_name: ["klikkflow-backend", "klikkflow-worker", "klikkflow-frontend"]

  alert:
  - "email"
  - "slack"

  email:
  - "ops@klikkflow.com"
  - "dev@klikkflow.com"

  slack:
    slack_webhook_url: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"
    slack_channel_override: "#alerts"
    slack_username_override: "ElastAlert"

  alert_text: |
    High error rate detected in KlikkFlow applications.

    Service: {0}
    Error Count: {1}
    Time Window: 5 minutes

    Recent errors:
    {2}
  alert_text_args:
    - service_name
    - num_matches
    - message

  include:
    - service_name
    - log_level
    - message
    - "@timestamp"
    - trace_id
    - execution_id

---

# Failed workflow executions alert
- name: "KlikkFlow Failed Workflow Executions"
  type: frequency
  index: klikkflow-logs-*
  num_events: 5
  timeframe:
    minutes: 10

  filter:
  - terms:
      log_level: ["error"]
  - exists:
      field: "workflow_id"
  - terms:
      message: ["workflow execution failed", "workflow error", "execution failed"]

  alert:
  - "email"
  - "slack"
  - "pagerduty"

  email:
  - "ops@klikkflow.com"
  - "product@klikkflow.com"

  pagerduty:
    pagerduty_service_key: "YOUR_PAGERDUTY_SERVICE_KEY"
    pagerduty_client_name: "ElastAlert"

  alert_text: |
    Multiple workflow executions are failing.

    Failed Executions: {0}
    Time Window: 10 minutes

    Affected Workflows:
    {1}
  alert_text_args:
    - num_matches
    - workflow_id

  include:
    - workflow_id
    - execution_id
    - log_level
    - message
    - "@timestamp"
    - error_message

---

# Database connection errors
- name: "KlikkFlow Database Connection Errors"
  type: frequency
  index: klikkflow-logs-*
  num_events: 3
  timeframe:
    minutes: 5

  filter:
  - terms:
      log_level: ["error"]
  - query:
      query_string:
        query: 'message:("connection refused" OR "connection timeout" OR "database error" OR "ECONNREFUSED")'

  alert:
  - "email"
  - "slack"
  - "pagerduty"

  email:
  - "dba@klikkflow.com"
  - "ops@klikkflow.com"

  alert_text: |
    Database connection errors detected.

    Error Count: {0}
    Service: {1}

    This indicates potential database connectivity issues.
  alert_text_args:
    - num_matches
    - service_name

---

# HTTP 5xx errors spike
- name: "KlikkFlow HTTP 5xx Errors"
  type: frequency
  index: klikkflow-logs-*
  num_events: 15
  timeframe:
    minutes: 5

  filter:
  - range:
      http_status_code:
        gte: 500
        lt: 600

  alert:
  - "email"
  - "slack"

  email:
  - "dev@klikkflow.com"
  - "ops@klikkflow.com"

  alert_text: |
    High number of HTTP 5xx errors detected.

    Error Count: {0}
    Status Codes: {1}
    Time Window: 5 minutes

    This indicates potential application issues.
  alert_text_args:
    - num_matches
    - http_status_code

  include:
    - http_status_code
    - http_method
    - http_url
    - response_time
    - service_name
    - "@timestamp"

---

# Slow response times
- name: "KlikkFlow Slow Response Times"
  type: frequency
  index: klikkflow-logs-*
  num_events: 10
  timeframe:
    minutes: 5

  filter:
  - range:
      response_time:
        gte: 5000  # 5 seconds
  - exists:
      field: "response_time"

  alert:
  - "email"
  - "slack"

  email:
  - "dev@klikkflow.com"

  alert_text: |
    Slow response times detected.

    Slow Requests: {0}
    Average Response Time: {1}ms
    Time Window: 5 minutes
  alert_text_args:
    - num_matches
    - response_time

---

# Security alerts - Failed authentication
- name: "KlikkFlow Failed Authentication Attempts"
  type: frequency
  index: klikkflow-logs-*
  num_events: 20
  timeframe:
    minutes: 10

  filter:
  - terms:
      log_level: ["warn", "error"]
  - query:
      query_string:
        query: 'message:("authentication failed" OR "invalid credentials" OR "unauthorized" OR "login failed")'

  alert:
  - "email"
  - "slack"

  email:
  - "security@klikkflow.com"
  - "ops@klikkflow.com"

  slack:
    slack_channel_override: "#security-alerts"

  alert_text: |
    High number of failed authentication attempts detected.

    Failed Attempts: {0}
    Time Window: 10 minutes
    Client IPs: {1}

    This could indicate a potential security threat.
  alert_text_args:
    - num_matches
    - client_ip

  include:
    - client_ip
    - user_agent
    - message
    - "@timestamp"

---

# Disk space warnings from system logs
- name: "KlikkFlow Disk Space Warning"
  type: any
  index: klikkflow-logs-*

  filter:
  - query:
      query_string:
        query: 'message:("disk space" OR "filesystem full" OR "no space left")'
  - terms:
      log_level: ["warn", "error"]

  alert:
  - "email"
  - "slack"
  - "pagerduty"

  email:
  - "ops@klikkflow.com"

  alert_text: |
    Disk space warning detected on server.

    Server: {0}
    Message: {1}

    Please check disk usage immediately.
  alert_text_args:
    - host.name
    - message

---

# Memory usage warnings
- name: "KlikkFlow High Memory Usage"
  type: frequency
  index: klikkflow-logs-*
  num_events: 5
  timeframe:
    minutes: 15

  filter:
  - query:
      query_string:
        query: 'message:("out of memory" OR "memory allocation failed" OR "heap overflow")'
  - terms:
      log_level: ["error", "fatal"]

  alert:
  - "email"
  - "slack"
  - "pagerduty"

  email:
  - "ops@klikkflow.com"
  - "dev@klikkflow.com"

  alert_text: |
    High memory usage or memory errors detected.

    Incidents: {0}
    Service: {1}

    Please investigate memory usage patterns.
  alert_text_args:
    - num_matches
    - service_name

---

# Integration failures
- name: "KlikkFlow Integration Failures"
  type: frequency
  index: klikkflow-logs-*
  num_events: 5
  timeframe:
    minutes: 10

  filter:
  - terms:
      log_level: ["error"]
  - query:
      query_string:
        query: 'message:("integration failed" OR "api call failed" OR "third party error")'

  alert:
  - "email"
  - "slack"

  email:
  - "dev@klikkflow.com"
  - "product@klikkflow.com"

  alert_text: |
    Multiple integration failures detected.

    Failed Integrations: {0}
    Integration Names: {1}

    Please check third-party service status.
  alert_text_args:
    - num_matches
    - integration_name

---

# Certificate expiration warnings
- name: "KlikkFlow Certificate Expiration"
  type: any
  index: klikkflow-logs-*

  filter:
  - query:
      query_string:
        query: 'message:("certificate expir" OR "cert expir" OR "ssl expir" OR "tls expir")'
  - terms:
      log_level: ["warn", "error"]

  alert:
  - "email"
  - "slack"

  email:
  - "ops@klikkflow.com"
  - "security@klikkflow.com"

  alert_text: |
    SSL/TLS certificate expiration warning.

    Certificate: {0}
    Expiration Date: {1}

    Please renew the certificate before expiration.
  alert_text_args:
    - certificate_name
    - expiration_date

---

# Application startup/shutdown alerts
- name: "KlikkFlow Service Status Changes"
  type: any
  index: klikkflow-logs-*

  filter:
  - query:
      query_string:
        query: 'message:("application started" OR "application stopped" OR "service started" OR "service stopped" OR "server shutdown")'
  - terms:
      log_level: ["info", "warn"]

  alert:
  - "email"
  - "slack"

  email:
  - "ops@klikkflow.com"

  alert_text: |
    Service status change detected.

    Service: {0}
    Status: {1}
    Time: {2}
  alert_text_args:
    - service_name
    - status
    - "@timestamp"

# Global alert settings
alert_text_type: alert_text_only
alert_text_kw:
  num_matches: num_matches
  terms_size: 50

# Enhancement modules
enhancement:
- "elastalert.enhancements.TimeEnhancement"
- "elastalert.enhancements.PercentMatchEnhancement"

# Include/exclude fields in alerts
include:
- "@timestamp"
- "service_name"
- "log_level"
- "message"
- "host.name"

# Generate kibana discover URLs
generate_kibana_discover_url: true
kibana_discover_app_url: "http://kibana:5601/#/discover"
kibana_discover_version: "7.10"
kibana_discover_index_pattern_id: "klikkflow-logs-*"

# Custom fields for better context
top_count_keys:
- "service_name"
- "log_level"
- "client_ip"

# Alert frequency limits
realert:
  minutes: 10

# Exponential realert
exponential_realert:
  hours: 1