name: ci

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-and-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm lint
      - name: Duplicate check (jscpd)
        run: pnpm dup:check
      - name: Build (filtered for speed)
        run: pnpm build
      - name: Type-check
        run: pnpm type-check

