name: jscpd-duplicate-check

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  jscpd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.18.1
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run jscpd duplicate check
        run: pnpm dup:check

